In [ ]:
=========================== EDA ==========================
1.pandas >>>>>>>>>>>>>>>>>>> :data frame or data application      
2.numpy   >>>>>>>>>>>>>>>>>> :numerical python formath operation
3.matplotlib >>>>>>>>>>>>>> :for plot graph
4.seaborn >>>>>>>>>>>>>>>>>> :for plot graph
5.bokhe >>>>>>>>>>>>>>>>>>> :for plots
6.plotly >>>>>>>>>>>>>>>>>> :for plots
=======================machine learning ================

7. scikit learn (sklearn) : ml models
8. stats                  : statistical model
    
====================== data retrival from sql scrapping =========

9. sqlite                 : connect with data base
10. Beautiful soup         : scrap the data from website
11.websocket               : scrap

====================== Deep learning / computer vission ============================
12.tensorflow                : google
13: keras                    : dl model
14.open cv                   : image operation
15.pillow(pil)               : image opeartion
16.pytorch                   : facebook
17.pretrained models         :
    ( VGG 16 , mobilenet,
     RESNET, RCNN,MASKRCNN,
     FASTER CNN,YOLO)
==================== natural language process(NLP) =======================
18.NLTK                     : natural language process
19.scipy                    
20.word2vec (how word will convert into vector)
21.glove
22.wordcloud

==================== hugging face ============================
23.transormers             : BERT 

========================== GenAI models=======================
24.openAI+microsoft       :  GPT models
25.google                 : gemini
26.amazon                 : q
27.meta                   : meta ai
28.apple

========================== LANGCHAIN ===============================
29.langchain framework
=========================== deployment ============================
30.flask
31.streamlit
32.Django
========================== mlops============================
33.mlflow
34.kubeflow
35.azure ai services : zure package
36.Gcp                : gcp package

**step-1**
- **data frame**

- we will create a data frame using list
- we will create a data frame uing dict 

In [12]:
import pandas as pd

In [13]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [14]:
type(d1)

pandas.core.frame.DataFrame

**step-2**
- **provide the data**

In [15]:
names=['tarun','surender','mohit']
pd.DataFrame(names)

0
0     tarun
1  surender
2     mohit

In [16]:
names=['tarun','surender','mohit']
age=[20,21,22]
data=zip(names,age)
pd.DataFrame(data)

0   1
0     tarun  20
1  surender  21
2     mohit  22

In [17]:
names=['tarun','surender','mohit']
age=[20,21,22]
city=['hyd','ecil','blr']
data=zip(names,age,city)
pd.DataFrame(data)

0   1     2
0     tarun  20   hyd
1  surender  21  ecil
2     mohit  22   blr

**step-3**
- **provide the column names**

In [18]:
names=['tarun','surender','mohit']
pd.DataFrame(names,columns=['names'])


names
0     tarun
1  surender
2     mohit

In [19]:
names=['tarun','surender','mohit']
age=[20,21,22]
data=zip(names,age)
pd.DataFrame(data,columns=['name','age'])

name  age
0     tarun   20
1  surender   21
2     mohit   22

In [20]:
names=['tarun','surender','mohit']
age=[20,21,22]
city=['hyd','ecil','blr']
data=zip(names,age,city)
cols=['names','age','city']
pd.DataFrame(data,columns=cols)

names  age  city
0     tarun   20   hyd
1  surender   21  ecil
2     mohit   22   blr

In [21]:
names=['tarun','surender','mohit']
age=[20,21,22]
city=['hyd','ecil','blr']
data=zip(names,age,city)
ix=['a','b','c']
cols=['names','age','city']
pd.DataFrame(data,index=ix,columns=cols)

names  age  city
a     tarun   20   hyd
b  surender   21  ecil
c     mohit   22   blr

In [22]:
names=['tarun','surender','mohit']
age=[20,21,22]
city=['hyd','ecil','blr']
data=zip(names,age)

cols=['names','age']
pd.DataFrame(data,index=city,columns=cols)

names  age
hyd      tarun   20
ecil  surender   21
blr      mohit   22

**step-5**
- add a new column on existing dataframe

In [23]:
import pandas as pd

In [24]:
names=['shuv','shyam','hari']
age=[22,45,59]
city=['bbsr','cutt','ken']
df=pd.DataFrame(zip(names,age,city))
df

0   1     2
0   shuv  22  bbsr
1  shyam  45  cutt
2   hari  59   ken

- if you want to add a new column 
- first check how many rows are there.
- for example in above dataframe we have 3 rows.
- sppose i wanrt to write a new column called salary.
- make a list with 3 values
- salary=[100000,200000,300000]
**syntax** : Dataframe[column]=list of values

In [25]:
salary=[100000,200000,300000]
df['salary']=salary
df

0   1     2  salary
0   shuv  22  bbsr  100000
1  shyam  45  cutt  200000
2   hari  59   ken  300000

**use case-1**
- create empty data frame first
- create 3 list using list comprehension
- list1=a values frome 1 to 10
- list2=square of 1 to 10
- list3=cube of 1 to 10
- finally make a data frame.

In [26]:
import pandas as pd

In [27]:
list1=[i for i in range(1,11)]
list2=[i*i for i in range(1,11)]
list3=[i*i*i for i in range(1,11)]
col=['number','square','cube']
df=pd.DataFrame(zip(list1,list2,list3),columns=col)
df

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729
9      10     100  1000

**step-6**
**update already exsisted column**
- create a new column
  - creating a new list    salary=[100000,200000,300000]
  - create a new column the column name is our choice.
- update existing column are same way only
   - here also we need make a list of values = number of rows
   - while updating the existing column
   - we need to provide already existed column name only


In [28]:
list3=[i**4 for i in range(1,11)]
df['cube']=list3
df

number  square   cube
0       1       1      1
1       2       4     16
2       3       9     81
3       4      16    256
4       5      25    625
5       6      36   1296
6       7      49   2401
7       8      64   4096
8       9      81   6561
9      10     100  10000

**step-7**
- **Drop the column**

In [29]:
# how to check columns
df.columns

Index(['number', 'square', 'cube'], dtype='object')

- if you want to drop a specific column
- we will use drop column
- keyward will use directly
- method we will use with corresponding dataframe
- **method name : drop**

- column : which column you want to drop
- axis : represents the specified value is a row or column
- axis = 0 means row
- axis = 1 means column
- inplace : will rovide overwrite the dataframe or not
   - inplace= True,this indicates overwrite the dataframe
  - inplace=False , this indicates the modified dataframe will be use when you provide new variable foer the operation

In [30]:
df.drop

<bound method DataFrame.drop of    number  square   cube
0       1       1      1
1       2       4     16
2       3       9     81
3       4      16    256
4       5      25    625
5       6      36   1296
6       7      49   2401
7       8      64   4096
8       9      81   6561
9      10     100  10000>

In [31]:
df.drop('cube',axis=1)

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81
9      10     100

In [32]:
df
# we will see original dataframe
# because we did not provide inplace.

number  square   cube
0       1       1      1
1       2       4     16
2       3       9     81
3       4      16    256
4       5      25    625
5       6      36   1296
6       7      49   2401
7       8      64   4096
8       9      81   6561
9      10     100  10000

**step-8**
- **Drop the row**
- drop the column and drop the rows both ae similar only
- the only difference is axis
- by default axis=0 available
- which means if we provided the value it will represents rows only

In [33]:
import pandas as pd

In [34]:
list1=[i for i in range(1,11)]
list2=[i*i for i in range(1,11)]
list3=[i*i*i for i in range(1,11)]
col=['number','square','cube']
df=pd.DataFrame(zip(list1,list2,list3),columns=col)
df

number  square  cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729
9      10     100  1000

In [35]:
df.drop('number')
# if we will run this it ives error
# by default axis =0 which represents about rows
#but 'number' is a column
# if you want to drop row,the provide the row index

KeyError: "['number'] not found in axis"

In [ ]:
df.drop(4)

In [ ]:
# multiple row drop
df.drop([4,8,6])

In [ ]:
df.drop([0,1],axis=1)
#[0,1]  : index
#axis =1 columns
#error

In [36]:
df.columns

Index(['number', 'square', 'cube'], dtype='object')

**step-9**
- **how to select the column**

In [37]:
df['number']
# series type
# no column name display
# when ever you see this type : series type

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: number, dtype: int64

In [38]:
df.number                 # df['number'] same as df.number

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: number, dtype: int64

In [39]:
df[['square']]
# Data frame 

square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81
9     100

In [40]:
type(df[['square']])  # [[]]

pandas.core.frame.DataFrame

In [41]:
type(df['square'])   # []

pandas.core.series.Series

In [42]:
df[['number','square']]

number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81
9      10     100

In [43]:
df['number'].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

-  all values come in an array
- array means it is a list of element only represent using numpy package
- generally element present in 4 ways
- numpy : array
- list : basic represemtation
- tensors : tensorflow package
- torch : pytorch package

In [44]:
list1=[1,3,2,4]

In [45]:
import numpy as np
np.array(list1)

array([1, 3, 2, 4])

In [46]:
list1=[1,3,2,4,5,9,3,6]
list2=[1,3,2,4,6,7,4,6]
list1+list2

[1, 3, 2, 4, 5, 9, 3, 6, 1, 3, 2, 4, 6, 7, 4, 6]

In [47]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([ 2,  6,  4,  8, 11, 16,  7, 12])

In [48]:
df["NUMBER"]=df['number'].values
df

number  square  cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9
9      10     100  1000      10

- imagine we worked on an ml
- we got some series of values
- with that series of values also we can create a dataframe

**step-10**
- **save the data frame**
   - we can save in two formats
   - csv : comma separated value
   - xlsx : exel format
- in order to save any data
   - where you want to save : directory name
   - what is the name of the file for storing
   - what is the extension
- we already seen same in file handling session

In [49]:
# case - 1 sving file at same location
# no need to provided directory path
# directory give only name of the file
# and extension

In [50]:
# dataframe name : df
df.to_csv('Data1.csv')
df.to_excel('Data1.xlsx')

**step-11**
- **How to read a dataframe**

In [51]:
import pandas as pd

In [52]:
pd.read_csv('Data1.csv')

Unnamed: 0  number  square  cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9
9           9      10     100  1000      10

In [53]:
# import os 
# os.cwd

In [54]:
pd.read_excel('Data1.xlsx')

Unnamed: 0  number  square  cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9
9           9      10     100  1000      10

**step-12**
- **how to avoid index column**
- while we save the dataframe
- automatically a new column will create
- that we need to avoid
- permission denied means close the data file from laptop

In [55]:
pd.to_csv('Data1.csv',index=False)
pd.to_excel('Data1.xlsx',index=False)

AttributeError: module 'pandas' has no attribute 'to_csv'

In [56]:
df.to_csv('Data1.csv')
df.to_excel('Data1.xlsx')